### ISSUE TITLE
I would like to join *team*

### ISSUE THREAD

**Issue by manthanchauhan** [socialat/team#10]
As you're willing to get support for your open source project, please let us know followings;

1. Name of the team who can help you better (max 5).
2. Description of your project :
3. Link of your project :
4. Link for the documentation: (link / NA)
5. Does it has good test coverage? (Yes/ No/ NA)
6. Is it first timers friendly? (Yes/ No/ NA)
7. What kind of support you're looking for?
8. Would you like to join *team* to support other seekers?

Please [bookmark](https://github.com/socialat/team/stargazers) for future updates.

**Comment by amitguptagwl** [comment]
Thanks for your support. I believe you would like to join the team as a developer/intern? Otherwise, please let me know.

You must have received an invitation link to accept.

**Comment by manthanchauhan** [comment]
I would like to join as a developer

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by amitguptagwl** [comment]
Invitation sent.
