### ISSUE TITLE
Intern Team Application

### ISSUE THREAD

**Issue by ashishpatelcs** [socialat/team#5]
Thanks to take care of open source community and to join us. Please fill the below template so that we can add you as a team member in appropriate team.

1. Are you active open source developer? - Yes
2. Have you contributed in any open source project which is not created by you? - Yes
3. Team you want to join? (You can join up to 5 teams. But one team at a time) - Intern, Developers
4. Teams you want to leave? - None

You can join either `intern` or other teams.
To join *team* team, you need to be active in opensource development from at least last 3 months.

Please [bookmark](https://github.com/socialat/team/stargazers) for future updates.

**Comment by amitguptagwl** [comment]
Thanks Ashish. You should receive an invitation on your registered email id to join team.
