### ISSUE TITLE
A collaboration project for interns

### ISSUE THREAD

**Issue by ashishpatelcs** [socialat/team#8]
**Is your feature request related to a problem? Please describe.**
It would be great to have a collaboration project for interns.

**Describe the solution you'd like**
In this project, every intern joining open source for the first time, would make a PR request with a small change like adding their names to contributors.md list and push the code. 

**Additional context**

Please [bookmark](https://github.com/socialat/team/stargazers) for future updates.

**Comment by amitguptagwl** [comment]
It's not a bad idea. But I had found some projects doing the same thing. Instead, I've made a project [imglab](https://github.com/NaturalIntelligence/imglab/) where many issues require just 2-mins work and give the feeling of real contribution. So probably we can think about some innovative project for contribution which give a real feel to contributors and teach the concepts of github as well. E.g. writing a book.

Please also check [collabs](https://github.com/socialat/collabs) project for new ideas.

**Comment by amitguptagwl** [comment]
@ashishpatelcs I've created #9 issue which has a collection of issues can be picked by interns. I'll add more in the future.
